import { AlertTriangle, BriefcaseMedical, Calendar, Car, CheckCircle, Eye, Heart, HeartPulse, Snowflake, Syringe, Thermometer, Utensils } from "lucide-react";
import { PageShell } from "../../components/PageShell";
import { PageHero } from "../../components/PageHero";
import { InfoCard, List, QuickTopicRow, SectionTitle, StatRow, StepGrid } from "../../components/Cards";

export default function PreventionPage() {
  return (
    <PageShell active="/prevention">
      <PageHero title="Prevention" subtitle="How to help prevent hypoglycemia before it starts." body="Most hypoglycemia episodes can be reduced or prevented through careful feeding, warmth, observation, reduced stress, and close attention to tiny puppies, especially Chihuahuas and other toy puppies." image="/images/prevention-hero.png" primary={{ label: "Prevention Checklist", href: "#routine" }} secondary={{ label: "When Risk Is Higher", href: "#risk" }} sideCard={<><h3>Daily Prevention Basics</h3><ol><li>Feed on schedule</li><li>Keep warm</li><li>Limit overexertion</li><li>Watch for early signs</li><li>Keep Pup-Lift nearby</li></ol><p className="script">Good prevention can stop an emergency before it begins.</p></>} />
      <QuickTopicRow topics={[{ icon: Utensils, title: "Feed consistently", text: "Small, frequent meals support stable blood sugar." }, { icon: Thermometer, title: "Keep puppy warm", text: "Warmth helps prevent energy loss." }, { icon: Eye, title: "Watch closely", text: "Early signs are easier to spot when paying attention." }]} />
      <QuickTopicRow topics={[{ icon: Utensils, title: "Feeding Schedule" }, { icon: Thermometer, title: "Warmth & Comfort" }, { icon: HeartPulse, title: "Stress & Activity" }, { icon: AlertTriangle, title: "High-Risk Situations" }, { icon: BriefcaseMedical, title: "Prevention Supplies" }, { icon: Calendar, title: "Daily Monitoring" }]} />
      <section className="card-grid four"><InfoCard icon={ShieldHeart} title="Why Prevention Matters"><p>Toy puppies have small glycogen reserves, little body fat, and high energy needs. Missed meals, chilling, or stress can lead to a rapid drop in blood sugar.</p></InfoCard><InfoCard icon={Utensils} title="Feeding Schedule"><List good items={["Feed small, frequent meals.", "Do not skip feedings.", "Follow breeder/vet feeding instructions.", "Offer food promptly after play or stress.", "Keep a consistent daily rhythm."]} /></InfoCard><InfoCard icon={Thermometer} title="Keep Your Puppy Warm"><List good items={["Avoid chilling at all times.", "Dry puppy well if damp.", "Provide cozy bedding.", "Avoid drafts and cold floors.", "Monitor tiny puppies closely in cool weather."]} /></InfoCard><InfoCard icon={HeartPulse} title="Limit Stress & Overexertion"><List good items={["Avoid rough play when puppy is tired.", "Prevent long periods without rest.", "Reduce stress during travel or big changes.", "Supervise children handling tiny puppies.", "Keep routines calm and steady."]} /></InfoCard></section>
      <StatRow items={[{ icon: Heart, title: "Toy breeds", text: "Highest risk due to size and reserves." }, { icon: Calendar, title: "First 6 months", text: "Highest-risk age window." }, { icon: DropletIcon, title: "80-120 mg/dL", text: "Typical healthy canine blood glucose range." }, { icon: HeartPulse, title: "Around 60 mg/dL", text: "Where hypoglycemia becomes a major concern." }]} />
      <SectionTitle>When Risk Is Higher</SectionTitle>
      <section id="risk" className="card-grid six-cards">{[{ icon: Utensils, title: "Missed Meals" }, { icon: Snowflake, title: "Cold Temperatures" }, { icon: Car, title: "Stress or Travel" }, { icon: AlertTriangle, title: "Illness or Vomiting" }, { icon: HeartPulse, title: "Heavy Play" }, { icon: Heart, title: "Very Small Puppies" }].map(({ icon, title }) => <InfoCard key={title} icon={icon} title={title}><p>Extra attention is needed because risk can rise quickly in this situation.</p></InfoCard>)}</section>
      <SectionTitle>Daily Prevention Routine</SectionTitle>
      <div id="routine"><StepGrid columns="five" steps={["Morning meal and check-in", "Warmth and comfort", "Midday monitoring", "Evening meal and calm routine", "Bedtime check and supplies ready"].map((title) => ({ title, text: "Keep food, warmth, and observation consistent through the day." }))} /></div>
      <section className="two-panels"><InfoCard icon={Syringe} title="Prevention Supplies to Keep Nearby"><img className="bottle-float small-bottle" src="/images/pup-lift-bottle.png" alt="Pup-Lift bottle" /><List good items={["Pup-Lift bottle", "Small blanket or heating pad", "Puppy food and treats", "Clean water", "Breeder/Vet contact info", "Feeding reminder routine"]} /></InfoCard><InfoCard icon={Eye} title="Signs to Watch Even During Prevention"><List good items={["Weakness or low energy", "Wobbling or unsteady", "Poor appetite", "Cold body or extremities", "Crying or unusual fussiness", "Tremors or shaking"]} /></InfoCard></section>
      <SectionTitle>What Owners Should Remember</SectionTitle>
      <StatRow items={[{ icon: Eye, title: "Observation Matters", text: "Know normal behavior and watch for changes." }, { icon: Calendar, title: "Consistency Matters", text: "Routine feeding and warmth keep blood sugar stable." }, { icon: Heart, title: "Preparation Matters", text: "Keep Pup-Lift and emergency knowledge ready." }]} />
      <div className="disclaimer"><span>Hypoglycemia is often preventable with proper feeding, warmth, and observation, but it can still happen.</span><strong>Hypoglycemia is not covered under the health guarantee because it is considered preventable.</strong></div>
      <SectionTitle action={<a href="/faq">View All FAQs →</a>}>Frequently Asked Questions</SectionTitle>
      <section className="card-grid four"><InfoCard title="How often should I feed a tiny puppy?"><p>Most tiny puppies need small, frequent meals every 2-4 hours.</p></InfoCard><InfoCard title="What if my puppy misses a meal?"><p>Offer food as soon as you can and watch closely for signs.</p></InfoCard><InfoCard title="Should I worry during travel?"><p>Yes. Travel and stress can increase risk.</p></InfoCard><InfoCard title="Can prevention still fail?"><p>Yes. Be prepared and act quickly if you see signs.</p></InfoCard></section>
    </PageShell>
  );
}

function ShieldHeart(props) { return <Heart {...props} />; }
function DropletIcon(props) { return <CheckCircle {...props} />; }
