import { AlertTriangle, ClipboardList, Eye, Heart, HeartPulse, Home, Phone, Shield, Stethoscope, Thermometer, Utensils } from "lucide-react";
import { PageShell } from "../../components/PageShell";
import { PageHero } from "../../components/PageHero";
import { InfoCard, List, QuickTopicRow, SectionTitle, StatRow, StepGrid } from "../../components/Cards";

export default function AftercarePage() {
  return (
    <PageShell active="/aftercare">
      <PageHero title="Aftercare" subtitle="What to do after your puppy begins to respond." body="Once your puppy perks up, recovery is not over yet. Continue close care with monitoring, warmth, feeding, hydration, and watching for any signs that symptoms may return." image="/images/aftercare-hero.png" primary={{ label: "Recovery Checklist", href: "#timeline" }} secondary={{ label: "When to Call the Vet", href: "#vet" }} sideCard={<><h3>Immediate Aftercare</h3><ol><li>Keep puppy warm.</li><li>Watch closely for 30-60 minutes.</li><li>Offer a small meal once fully alert.</li><li>Continue checking energy, temperature, and responsiveness.</li><li>Contact a veterinarian if symptoms return or the puppy worsens.</li></ol><p className="script">Early recovery still needs close observation.</p></>} />
      <QuickTopicRow topics={[{ icon: Heart, title: "Monitor closely", text: "Watch for any changes in energy or behavior." }, { icon: Thermometer, title: "Warmth still matters", text: "Keep your puppy cozy and comfortable." }, { icon: Utensils, title: "Feed once alert", text: "Offer a small meal when swallowing safely." }]} />
      <QuickTopicRow topics={[{ icon: Home, title: "Warmth & Rest" }, { icon: Utensils, title: "Food & Hydration" }, { icon: Heart, title: "Monitoring" }, { icon: Stethoscope, title: "When to Call the Vet" }, { icon: Shield, title: "Preventing Another Drop" }, { icon: ClipboardList, title: "Owner Notes" }]} />
      <section className="card-grid four"><InfoCard icon={Shield} title="Why Aftercare Matters"><p>Even when your puppy improves, blood sugar can drop again. Careful aftercare helps prevent another emergency and supports a full recovery.</p></InfoCard><InfoCard icon={Thermometer} title="Keep Your Puppy Warm & Calm"><List items={["Keep wrapped in a light blanket.", "Avoid chilling or drafts.", "Use your body warmth.", "Avoid overheating.", "Keep the environment quiet.", "Reduce rough handling."]} /></InfoCard><InfoCard icon={Utensils} title="Feed Once Fully Alert"><List items={["Only feed when swallowing safely.", "Offer a small meal or breeder-approved food.", "Use small, frequent feedings.", "Do not force food.", "Continue normal feeding schedule once stable."]} /></InfoCard><InfoCard icon={Eye} title="Watch for Returning Signs"><List items={["Weakness or wobbling", "Crying or glassy eyes", "Trembling or shaking", "Unusual sleepiness", "Cold body or ears", "Poor appetite", "Collapse or unresponsiveness"]} /></InfoCard></section>
      <StatRow items={[{ icon: Heart, title: "30-60 minutes", text: "Minimum close monitoring after improvement." }, { icon: Utensils, title: "Small meals", text: "Help stabilize recovery." }, { icon: Heart, title: "Warm & calm", text: "Supports energy conservation." }, { icon: Shield, title: "If signs return", text: "Repeat steps and contact your vet." }]} />
      <SectionTitle>Recovery Timeline</SectionTitle>
      <div id="timeline"><StepGrid columns="five" steps={["Warm & observe", "Puppy becomes alert", "Offer small meal", "Continue monitoring", "Resume routine carefully"].map((title) => ({ title, text: "Move slowly and keep watching for returning symptoms." }))} /></div>
      <section className="two-panels"><InfoCard icon={Utensils} title="What To Offer After Pup-Lift"><img className="bottle-float small-bottle" src="/images/pup-lift-bottle.png" alt="Pup-Lift bottle" /><List good items={["Small meal once fully alert and swallowing safely.", "Breeder-recommended food or high-quality puppy food.", "Fresh water once swallowing is safe.", "Small, frequent feedings over the next few hours.", "Avoid overfeeding at once."]} /></InfoCard><InfoCard icon={AlertTriangle} title="What To Avoid During Recovery"><List bad items={["No rough play or overexertion.", "No bathing if chilled or weakened.", "No forcing food, liquid, or treats.", "No leaving puppy alone during this period.", "No assuming the episode is over too soon."]} /></InfoCard></section>
      <SectionTitle>When Veterinary Care Is Still Needed</SectionTitle>
      <section id="vet" className="warning-grid">{["Seizure activity", "Collapse or unresponsiveness", "Not improving or worsening", "Cannot swallow", "Repeated episodes", "Blue or very pale gums"].map((t) => <div className="mini-card" key={t}><AlertTriangle size={38} /><h3>{t}</h3></div>)}<div className="mini-card call-card"><Phone size={40} /><h3>Call your vet immediately</h3><p>If recovery is incomplete or symptoms return.</p></div></section>
      <SectionTitle>Preventing Another Episode Today</SectionTitle>
      <StatRow items={[{ icon: ClipboardList, title: "Stay on schedule", text: "Keep feeding consistent." }, { icon: Thermometer, title: "Keep warm", text: "Avoid drafts and chilling." }, { icon: Heart, title: "Limit stress", text: "Prevent overexertion." }, { icon: Eye, title: "Monitor closely", text: "Watch through the day." }, { icon: SyringeBottle, title: "Keep Pup-Lift nearby", text: "Have it ready." }]} />
      <SectionTitle>What Owners Should Write Down</SectionTitle>
      <StatRow items={[{ icon: ClockIcon, title: "Time of episode and when it improved.", text: "Helps track patterns and prevention." }, { icon: ClipboardList, title: "Signs observed and how much Pup-Lift was used.", text: "Include how quickly your puppy responded." }, { icon: ClipboardList, title: "Food offered, response, and next steps.", text: "Note if vet follow-up is needed." }]} />
      <div className="disclaimer"><span>Hypoglycemia can improve quickly but still become serious again. <strong>Hypoglycemia is not covered under the health guarantee because it is considered preventable.</strong></span><span>This guidance supports emergency first-aid but does not replace veterinary advice.</span></div>
      <SectionTitle action={<a href="/faq">View All FAQs →</a>}>Frequently Asked Questions</SectionTitle>
      <section className="card-grid four"><InfoCard title="When can I feed my puppy after Pup-Lift?"><p>Only once your puppy is fully alert and swallowing safely.</p></InfoCard><InfoCard title="How long should I monitor?"><p>Monitor closely for at least 30-60 minutes after improvement.</p></InfoCard><InfoCard title="What if my puppy improves and then declines?"><p>Repeat emergency steps and contact your veterinarian.</p></InfoCard><InfoCard title="Can my puppy go back to normal activity?"><p>No. Resume routine slowly after stable recovery.</p></InfoCard></section>
    </PageShell>
  );
}

function SyringeBottle(props) { return <ClipboardList {...props} />; }
function ClockIcon(props) { return <HeartPulse {...props} />; }
